### ISSUE TITLE
Fetching a collection using defaults should not require the use of `yield`.

### ISSUE THREAD

**Issue by juanmac** [thomseddon/co-mongo#2]
Hi @thomseddon, when you say:

> Not all methods should be yielded, the rule is: if the methods accepts a callback (e.g. collection.insert()), yield it, if it doesn't (e.g. collection.find()) don't.

Please correct me if I'm wrong but according to [this docs](http://mongodb.github.io/node-mongodb-native/api-generated/db.html#collection), fetching a mongodb collection using defaults (specifically `{strict: false}`), the use of `yield` should not be necessary. For example doing something like this with thunkify should work:

```
var MongoClient = require("mongodb").MongoClient
, thunkify = require("thunkify")
, co = require('co')

co(function *() {
  MongoClient.connect = thunkify(MongoClient.connect)
  var db = yield MongoClient.connect('mongodb://localhost:27017/test');

  // fetch the collection without using yield
  var collection = db.collection("users");

  var cursor = collection.find()

  cursor.toArray = thunkify(cursor.toArray);
  var users = yield cursor.toArray()

  console.log(users)

  db.close();
});

```

but if you try it using co-mongo:

```
var comongo = require('co-mongo');
var co = require('co');

co(function *() {
  var db = yield comongo.connect('mongodb://127.0.0.1:27017/test');

  // try to fetch the collection without using yield
  var collection = db.collection('users');

  var cursor = collection.find();

  var users = yield cursor.toArray();

  console.log(users);

  db.close();
})();
```

it throws an error like this:

```
TypeError: Object function (done) {
  args.push(function (err, collection) {
    if (err) return done(err);

    if (Array.isArray(collection)) {
      collection = collection.map(function (collection) {
        return new Collection(collection);
      });
      return done(null, collection);
    }

    done(null, new Collection(collection));
  });
  db[method].apply(db, args);
} has no method 'find'
```

It might be a minor change but it could help to keep consistency with node-mongodb-native.
Cheers! :D

**Comment by thomseddon** [comment]
I did ponder this.....

Looking at it again, for the case where you do use `{ strict: true }` then you would have to yield it, we could look to see if `strict` has been set to `true` but I think i'd prefer to just keep a consistent API?

Perhaps we should just make a note of it?

**Comment by juanmac** [comment]
Yes of course, the api is consistent and actually after trying others like kongo or co-mongodb, co-mongo is the only one that actually works as espected. I just realize in the goals you expose in the readme and also in the fact that, at least in development, I rarely use callbacks to fetch collections and consequently my first attempt was to not use `yield`. However now reviewing the examples in the docs there is a case where the comments says `// Grab a collection with a callback but no safe operation` where it uses a callback even with `{safe : false}`... so perhaps just a little note will be enough. thanks for your work man!
